name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: install rsbuild
      run: cargo install rsbuild

    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend

    - name: Build backend
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Create deployment package
      run: |
        mkdir deploy
        cp target/x86_64-unknown-linux-gnu/release/kboard-cli deploy/
        cp -r config deploy/
        tar -czf deployment.tar.gz -C deploy .

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: deployment.tar.gz