name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-musl

    - name: Install musl tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: install rsbuild
      run: cargo install rsbuild

    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend

    - name: Build backend
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Run tests
      run: cargo test --verbose

    - name: Create deployment package
      run: |
        mkdir deploy
        mkdir -p deploy/frontend/
        cp target/x86_64-unknown-linux-musl/release/kboard-cli deploy/
        cp -r config deploy/
        cp -r frontend/dist/ deploy/frontend/
        echo "nohup ./kboard-cli start --environment production"
        tar -czf deployment.tar.gz -C deploy .

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: deployment.tar.gz